### PR TITLE
0.996 compatibility

### PR DESCRIPTION
**Pull request by markburns**
@keichan34 
I've not personally got the code from #1 to work on my machine, so I'm moving it out of master onto this branch for now and will update the README to notify people that they can try out this branch.

### CODE REVIEW

**Comment by keichan34** [comment]
Thanks.

I'm working on figuring out what the problem is now, but it seems like it might be a compiler issue? I tried using Travis on my fork: https://travis-ci.org/flagship-llc/mecab which is failing at the compile stage ( GCC 4.6 ). OS X / LLVM Clang 5.1 and GCC 4.2 works fine here, but GCC 4.8 fails as well. I'm working on getting GCC 4.6 installed so I can fix the Travis builds, then see what's going on with the "symbol not found" errors; I'll update you when I make some progress.

**Comment by keichan34** [comment]
I'm actually tempted to just include the whole mecab library within the gem, like [Nokogiri does with libxml2](https://github.com/sparklemotion/nokogiri/blob/3f1bec486f701a5cb3c2fee32e5e47cf9f759af3/ext/nokogiri/extconf.rb#L419), just to make sure the versions are consistent, but that might be overkill..

**Comment by markburns** [comment]
@keichan34 - if that works then I'd say do it. The whole reason for me creating this gem was to make it easier to install, and that certainly fits within that philosophy.

**Comment by keichan34** [comment]
Okay, I got Travis builds working: https://github.com/flagship-llc/mecab/tree/update-for-0.996

https://travis-ci.org/flagship-llc/mecab/builds/26352815

Can you try checking out that branch and see if it works?

**Comment by markburns** [comment]
I'm getting the following:

```
gem uninstall mecab && rake clean compile install            
Successfully uninstalled mecab-0.996
mkdir -p tmp/x86_64-darwin13.0/mecab/2.1.0
cd tmp/x86_64-darwin13.0/mecab/2.1.0
/Users/markburns/.rbenv/versions/2.1.0/bin/ruby -I. ../../../../ext/mecab/extconf.rb
checking for make... yes
checking for main() in -lstdc++... yes
checking for main() in -lmecab... yes
checking for main() in -lstdc++... yes
checking for mecab.h... yes
creating Makefile
cd -
cd tmp/x86_64-darwin13.0/mecab/2.1.0
make
compiling ../../../../ext/mecab/mecab_wrap.cpp
linking shared-object mecab.bundle
cd -
mkdir -p tmp/x86_64-darwin13.0/stage/lib
install -c tmp/x86_64-darwin13.0/mecab/2.1.0/mecab.bundle lib/mecab.bundle
cp tmp/x86_64-darwin13.0/mecab/2.1.0/mecab.bundle tmp/x86_64-darwin13.0/stage/lib/mecab.bundle
mecab 0.996 built to pkg/mecab-0.996.gem.
mecab (0.996) installed.

ruby examples/test.rb                                                                           
0.996
examples/test.rb:8:in `initialize': param.cpp(69) [ifs] no such file or directory: /usr/local/Cellar/mecab/0.996/lib/mecab/dic/ipadic/dicrc (RuntimeError)
    from examples/test.rb:8:in `new'
    from examples/test.rb:8:in `<main>'
```

**Comment by keichan34** [comment]
Hm. Is the homebrew `mecab-ipadic` package installed?

**Comment by markburns** [comment]
Yes, but as it says that file doesn't exist. Have you had this running on a Mac?

**Comment by keichan34** [comment]
Yeah. I'm running OS X 10.9.3 w/ Homebrew 0.9.5

```
$ brew info mecab
mecab: stable 0.996
http://mecab.sourceforge.net/
/usr/local/Cellar/mecab/0.996 (27 files, 54M) *
From: https://github.com/Homebrew/homebrew/commits/master/Library/Formula/mecab.rb

$ brew info mecab-ipadic
mecab-ipadic: stable 2.7.0-20070801
http://mecab.googlecode.com/svn/trunk/mecab/doc/index.html
/usr/local/Cellar/mecab-ipadic/2.7.0-20070801 (6 files, 16K) *
  Built from source
From: https://github.com/Homebrew/homebrew/commits/master/Library/Formula/mecab-ipadic.rb
==> Dependencies
Required: mecab ✔
==> Options
--charset=
    Select charset: utf8 (default), euc-jp, or sjis
```

Are the versions the same? Maybe uninstalling then re-installing mecab?

**Comment by markburns** [comment]
Yeah that was it, the versions were the same but the mecab install was 4MB, must have got screwed up somewhere along the line.
Great, thanks for all the hard work. I'll release the gem.

**Pull request merged**
