### PR TITLE
Adding header for OS X compilation

### PR DESCRIPTION
**Pull request by ippoippo**
Add OS X support

To allow native extensions to compile on OS X, I found it was necessary to copy the mecab.h file from the Mecab binary source code.

CentOS (our other deployment target) continues to build the Gem with no issues as far as I can see.

If there is a better approach that allows this Gem to be used in Gemfiles that are deployed on both CentOS and Mac OS X, would be happy to see that.

### CODE REVIEW

**Comment by markburns** [comment]
I didn't have this problem myself. Any idea why that might be? 

Would you mind confirming once more, that this definitely doesn't work for you as is, but does with this patch. Ideally a clean rvm/rbenv install.

Both your patch and the original work fine for me.

I'm happy to trust you, and merge changes in that makes it just work for more people, just want to double check that it's not just working by coincidence.

**Comment by markburns** [comment]
I'm going to guess you didn't `brew install`? Do you have a way you installed `mecab-ipadic` and `mecab` that meant the header file wasn't available?

**Comment by markburns** [comment]
Actually, if that's the case, then what I'd prefer to see is some kind of warnings/checks/prechecks when installing the gem. Ideally a fail-fast that recommends a `brew install` on OSX and/or uses `mdfind` to auto-populate a suggestion for altering your path to find the headers. 

Something like that. I suspect this solution might lead to more/harder to find problems by not failing as fast.

**Comment by ippoippo** [comment]
Hi Mark.

On my work dev Mac, I used `brew install` to install `mecab` and `mecab-ipadic` before I proceeded with the Gem install.

That said, I will double check this. I'll test on a clean Mac (my own personal one) when I get home.
So, that will be a clean homebrew install, followed by a clean me cab install. Downside is that my home machine is dev beta of Yosemite, work machine is Mavericks.

I'll let you know what happens.

BTW, I was getting the problem described here. Which is where I got the solution about copying the header file. Sorry , page is Japanese language.

http://qiita.com/skwbc/items/8c81b19bba221dfde133

**Comment by ippoippo** [comment]
Other details on work machine

We use rbenv. Global ruby (and project ruby) is `ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-darwin13.2.0]`

Homebrew version is `Homebrew 0.9.5`

**Comment by markburns** [comment]
I see. So since that post we've had an update to use the latest mecab version thanks to @keichan34.
Do you have the old mecab version installed?

**Comment by ippoippo** [comment]
Here you go...

```
gavin_thomas$ mecab -v
mecab of 0.996
```

**Comment by ippoippo** [comment]
Just check our CentOS machine. Same version (Centos, we build mecab binary from source)

**Comment by markburns** [comment]
Hmm, that's the right version. In that blog post, he isn't using this forked gem and he's using the old mecab. 

Let me know how it goes when you get home.

**Comment by ippoippo** [comment]
Will do.

**Comment by ippoippo** [comment]
Interesting!

Works fine on my machine at home.
https://github.com/ippoippo/mecab-quick-test

Basically I
1) Ensure my existing `rbenv` install was up to date
2) Ensure bundler was latest
3) Installed homebrew
4) Installed mecab
5) Ran bundle install on the project I created in repo above
6) Ran test code

**Comment by ippoippo** [comment]
I'll test against earlier Ruby version on my machine now... but I suspect the real fix is to ensure latest versions of software on my development machine at work. (which is strange, considering I built it only 1.5 months ago)

**Comment by ippoippo** [comment]
OK with earlier ruby versions.

Right, definitely the work machine setup... will investigate. I think you should hold off from merging PR. Don't close it yet though in case I discover something.

Thanks,
Gavin

**Comment by markburns** [comment]
:ok:

**Comment by markburns** [comment]
Any news on this? Closing, but feel free to re-open if so.

**Comment by ippoippo** [comment]
No problem in closing.
Given I was able to do a clean install on a separate Mac with no problems, it implies that I had messed up something on my own machine at work.

I've not had time to investigate further, and there is no rush for us to stop using our fork of this repo for now.

**Comment by ippoippo** [comment]
I started looking at this today.

Ran my test code (https://github.com/ippoippo/mecab-quick-test) on my work machine...

```
gavin-thomas-PN073s-MacBook-Pro:mecab-quick-test gavin_thomas$ bundle install
Fetching https://github.com/markburns/mecab.git
Fetching gem metadata from https://rubygems.org/..
Using bundler 1.6.3

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

    /Users/gavin_thomas/.rbenv/versions/2.0.0-p247/bin/ruby extconf.rb 
checking for make... yes
checking for main() in -lstdc++... yes
checking for main() in -lmecab... yes
checking for main() in -lstdc++... yes
checking for mecab.h... yes
creating Makefile

make "DESTDIR="
compiling mecab_wrap.cpp
mecab_wrap.cpp:1855:10: fatal error: 'mecab.h' file not found
#include "mecab.h"
         ^
1 error generated.
make: *** [mecab_wrap.o] Error 1


Gem files will remain installed in /Users/gavin_thomas/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/bundler/gems/mecab-3630ea7a0308 for inspection.
Results logged to /Users/gavin_thomas/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/bundler/gems/mecab-3630ea7a0308/ext/mecab/gem_make.out
An error occurred while installing mecab (0.996), and Bundler cannot continue.
Make sure that `gem install mecab -v '0.996'` succeeds before bundling.
```

I updated bundler to later version, `1.7.3`. Still same problem.

**Pull request closed without merging**
